name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Крок 1: Завантаження коду репозиторію
      - uses: actions/checkout@v2

      # Крок 2: Налаштування JDK (Java Development Kit)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          # Тимчасово видалено кеш
          # cache: maven

      # Крок 3: Очищення кешу Maven (опціонально)
      - name: Clear Maven Cache
        run: rm -rf ~/.m2/repository || true

      # Крок 4: Виконання збірки з Maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      # Крок 5: Перевірка результатів збірки (опціонально)
      - name: Post-build verification
        run: echo "Build completed successfully!"